# Simple workflow for deploying static content to Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['trunk']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug working directory
        run: ls -la ./tennis-schedule-reader-page

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./tennis-schedule-reader-page/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./tennis-schedule-reader-page
        
      - name: Install additional dependencies
        run: npm install -D sass-embedded
        working-directory: ./tennis-schedule-reader-page
        
      - name: Build
        run: npm run build
        working-directory: ./tennis-schedule-reader-page

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tennis-schedule-reader-page/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
