name: Trigger Notifications on New Bookings

on:
  push:
    branches:
      - trunk
    paths:
      - 'api/bookings_result_new.json'

  workflow_dispatch: # Allows manual triggering

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Load Subscriptions
        run: |
          echo "$SUBSCRIPTIONS_JSON" | base64 --decode > tennis-schedule-reader-page/subscriptions.json
        env:
          SUBSCRIPTIONS_JSON: ${{ secrets.SUBSCRIPTIONS_JSON }}

      - name: Install dependencies
        run: cd tennis-schedule-reader-page && npm install

      - name: Parse New Bookings and Trigger Notifications
        run: cd tennis-schedule-reader-page && node scripts/sendNotifications.js