name: Trigger Notifications on New Bookings

on:
  push:
    branches:
      - trunk
    paths:
      - 'api/bookings_result_new.json'

  workflow_dispatch: # Allows manual triggering

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Delete cached node_modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: cd tennis-schedule-reader-page && npm install

      - name: Debug installed dependencies
        run: ls -R tennis-schedule-reader-page/node_modules

      - name: Parse New Bookings and Trigger Notifications
        run: cd tennis-schedule-reader-page && node scripts/sendNotifications.js